# Machine Learning 
## 1.7 Introduction to Numpy
Plan:
  * Creating arrays
  * Multi dementional arrays
  * Randomly generated arrays
  * Element wise operations
    - Comparison operations
    - Logical operations
  * Summarizing operations


In [2]:
import numpy as np

## Creating arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10 , 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

List to numpy array

In [8]:
a = np.array([1,2,3,4,5,7,12])
a

array([ 1,  2,  3,  4,  5,  7, 12])

In [9]:
a[2]

3

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi dementional arrays

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
           [1,2,3],
           [4,5,6],
           [7,8,9]
           ])

In [16]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
n[1]

array([4, 5, 6])

In [21]:
n[:,1]

array([2, 5, 8])

In [22]:
n[:,2] = [0,1,2]

In [23]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [7, 8, 2]])

## Randomly generated arrays

In [30]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [31]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [33]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [35]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [37]:
a+100

array([100, 101, 102, 103, 104])

In [39]:
b = (10 + (a*2)) ** 2 / 100

In [40]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparision operations

In [41]:
a

array([0, 1, 2, 3, 4])

In [42]:
a >= 2

array([False, False,  True,  True,  True])

In [43]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [44]:
a>b

array([False, False,  True,  True,  True])

In [45]:
a[a>b]

array([2, 3, 4])

## Summarizing operations

In [46]:
a.min()

0

In [47]:
a.sum()

10